### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by ebottabi**

### CODE REVIEW

**Comment by jbouzekri** [comment]
Hi,
Is there a reason as to why you downgrade the pika version ?
Thanks

**Comment by joekarl** [comment]
Pretty sure this PR is like a year and a half old and not applicable now.
@lrobb this can probably closed (also I probably need to be removed from the wdt org)

**Comment by jbouzekri** [comment]
Okay. I am going to test this flask extension against the latest pika version. I will send a new pull request if I do not encounter any error.

**Comment by lrobb-zz** [comment]
thx @jbouzekri

**Pull request closed without merging**
